
"""
Script that acts on the data from a datastore and generates outputs.
"""
struct DinoScript
  path::String
  doc::String
  inputs::Vector{Symbol}
  outputs::Vector{Pair{Symbol, String}}
  f::Function
  env::Module
end

function _generate_dinoscript_env()
  env = Module(:DinoScriptEnv)
  Core.eval(env, quote
    using Statistics
    using Random
    using LinearAlgebra
  end)
  return env
end

_dino_output_pair(sym::Symbol) = sym => ""
_dino_output_pair(str::String) = Symbol(str) => ""
_dino_output_pair(t::Tuple) = Symbol(t[1]) => string(t[2])
_dino_output_pair(t::Pair) = Symbol(t[1]) => string(t[2])

_dino_result(t) = Dict([k => v for (k, v) in t])

function DinoScript(path::String)
  code = read(path, String)
  code = Meta.parseall(code; filename = path)
  env = _generate_dinoscript_env()
  Core.eval(env, code)

  doc = try
    env.doc
  catch _
    ""
  end

  inputs = try
    env.inputs
  catch _
    error("Script '$path' does not define 'inputs'.")
  end

  inputs = try
    [Symbol(input) for input in inputs]
  catch _
    error("Input declaration in script '$path' is malformed.")
  end

  outputs = try
    env.outputs
  catch _
    error("Script '$path' does not define 'outputs'.")
  end

  outputs = try
    [_dino_output_pair(s) for s in outputs]
  catch _
    error("Output declaration in script '$path' is malformed.")
  end

  f = try
    env.evaluate
  catch _
    error("Script '$path' does not define 'evaluate'.")
  end

  return DinoScript(path, doc, inputs, outputs, f, env)
end

function (script::DinoScript)(args...)
  result = try
    script.f(args...)
  catch err
    error("Script evaluation failed: $err.")
  end
  result = try
    _dino_result(result)
  catch
    error("Result format in script '$(script.path)' is malformed.")
  end
  for (name, _) in script.outputs
    if !haskey(result, name)
      error("Result in script '$(script.path)' misses output :$name.")
    end
  end
  return result
end

function Base.show(io::IO, ::MIME"text/plain", ds::DinoScript)
  println(io, "DinoScript")
  println(io, " doc: ", ds.doc)
  println(io, " inputs: ", ds.inputs)
  print(io, " outputs:")
  for pair in ds.outputs
    print(io, "\n  ", pair)
  end
  return
end

"""
    runscript(iterate, script::DinoScript, project::Project; variable_store)

Run the script `script` on the variable store with key `variable_store` in the
context generated by `project`.

After each call of the script, the variable store is updated via the function
`iterate(ctx, state)`. This is repeated until `iterate` returns the state
`nothing`.

Returns a vector of computed outputs.
"""
function runscript(
  script::DinoScript,
  project::Project;
  image_store,
  variable_store,
  variables = [],
  callback = (_, _) -> nothing,
)
  ctx = initcontext(project)
  store = loadcontext(ctx, image_store)
  vars = loadcontext(ctx, variable_store)

  for key in variables
    @assert haskey(vars, key) """
    The variable store does not define the requested variable :$key.
    """
  end
  for key in script.inputs
    @assert haskey(vars, key) """
    The variable store does not define the required input variable :$key.
    """
  end

  names = [:index; :path; variables; first.(script.outputs)]
  results = []
  nentries = length(store[:entries][])

  callback(0, nentries)
  notify(store[:select_first])

  for index in 1:nentries
    push!(results, store[:active_index][])
    push!(results, store[:entry][].path)
    for key in variables
      push!(results, vars[key][])
    end
    inputs = Dict(key => vars[key][] for key in script.inputs)
    outputs = script(inputs)
    for (key, _) in script.outputs
      push!(results, outputs[key])
    end
    callback(index, nentries)
    notify(store[:select_next])
  end

  result = permutedims(reshape(results, length(names), :))
  return names, result
end
